#ifndef INCLUDE_DFROBOT_ST7687S_REGS__
#define INCLUDE_DFROBOT_ST7687S_REGS__

#define DF_NOP 0x00            //
#define DF_SWRESET 0x01        //
#define DF_RDDST 0x09          //
#define DF_RDDPM 0x0A          //
#define DF_RDDMADCTR 0x0B      //
#define DF_RDDCOLMOD 0x0C      //
#define DF_RDDIM 0x0D          //
#define DF_RDDSM 0x0E          //
#define DF_SLPIN 0x10          //
#define DF_SLPOUT 0x11         //
#define DF_PTLON 0x12          //
#define DF_NORON 0x13          //
#define DF_INVOFF 0x20         //
#define DF_INVON 0x21          //
#define DF_APOFF 0x22          //
#define DF_APON 0x23           //
#define DF_WRCNTR 0x25         //
#define DF_DISPOFF 0x28        //
#define DF_DISPON 0x29         //
#define DF_CASET 0x2A          //
#define DF_RASET 0x2B          //
#define DF_RAMWR 0x2C          //
#define DF_RAMRD 0x2E          //
#define DF_PTLAR 0x30          //
#define DF_SCRLAR 0x33         //
#define DF_TEOFF 0x34          //
#define DF_TEON 0x35           //
#define DF_MADCTR 0x36         //
#define DF_VSCSAD 0x37         //
#define DF_IDMOFF 0x38         //
#define DF_IDMON 0x39          //
#define DF_COLMOD 0x3A         //
#define DF_RDID 0xDA           //
#define DF_DutySet 0xB0        //
#define DF_FirstCom 0xB1       //
#define DF_OscDiv 0xB3         //
#define DF_NLInvSet 0xB5       //
#define DF_ComScanDir 0xB7     //
#define DF_RmwIn 0xB8          //
#define DF_RmwOut 0xB9         //
#define DF_DispCompStep 0xBD   //
#define DF_VopSet 0xC0         //
#define DF_VopOfsetInc 0xC1    //
#define DF_VopOfsetDec 0xC2    //
#define DF_BiasSel 0xC3        //
#define DF_BstBmpXSel 0xC4     //
#define DF_VgSorcSel 0xCB      //
#define DF_IDSet 0xCC          //
#define DF_ANASET 0xD0         //
#define DF_AutoLoadSet 0xD7    //
#define DF_RDTstStatus 0xDE    //
#define DF_EEPCIN 0xE0         //
#define DF_EEPCOUT 0xE1        //
#define DF_EEPWR 0xE2          //
#define DF_EEPRD 0xE3          //
#define DF_ROMSET 0xE5         //
#define DF_LVMS 0xE8           //
#define DF_DispCompStep2 0xEC  //
#define DF_FRMSEL 0xF0         //
#define DF_FRM8SEL 0xF1        //
#define DF_TMPRNG 0xF2         //
#define DF_TMPHYS 0xF3         //
#define DF_TEMPSEL 0xF4        //
#define DF_THYS 0xF7           //
#define DF_FrameSet 0xF9       //
#define DF_EEPANFSEL 0xFA      //
#define DF_EEPERS 0xFB         //

#endif  // INCLUDE_DFROBOT_ST7687S_REGS__
